services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: LOG_CHANNEL
        value: errorlog
      - key: DB_CONNECTION
        value: pgsql
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
    buildCommand: echo "Build completed"
    startCommand: echo "Starting application"